#!/bin/bash

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile

# nvm installer checks for these patterns:       $NVM_DIR/nvm.sh & $NVM_DIR/bash_completion
# serverless installer checks for thist pattern: tabtab source for serverless package
# sls installer checks for thist pattern:        tabtab source for sls package


# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[ -f /Users/andre/.nvm/versions/node/v11.12.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash ] && . /Users/andre/.nvm/versions/node/v11.12.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash