#!/bin/bash

alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
alias code-insiders="/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin/code"