#!/bin/bash

run_node() {

    e_header "Installing NVM..."
    unset NVM_DIR
    curl -s -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [[ $? ]] && e_success "Done"

    e_header "Installing Node.js..."
    nvm install node
    nvm use node
    [[ $? ]] && e_success "Done"

    e_header "Installing Node.js packages..."
    local packages="npm serverless"
    npm install $packages --global --quiet
    [[ $? ]] && e_success "Done"

}

