#!/bin/bash

add_bind_mount() {
    DRIVE=$1
    printf "Bind mount for drive $DRIVE - "
    sudo mkdir -p /$DRIVE
    FSTAB_ENTRY="/mnt/$DRIVE                  /$DRIVE       none   bind            0 0"
    if grep -q "$FSTAB_ENTRY" /etc/fstab; then
        printf "skipped\n"
    	return
    fi	
    sudo echo "$FSTAB_ENTRY" >> /etc/fstab
    printf "added\n"
}

install_bind_mount() {
    e_header "Install Bind Mounts..."
    add_bind_mount "c"
    sudo mount -a 
    [[ $? ]] && e_success "Done"
}

is_wsl && install_bind_mount
