#!/bin/bash

install_docker_ubuntu() {

    e_header "Installing Docker..."

    # Environment variables you need to set so you don't have to edit the script below.
    export DOCKER_CHANNEL=edge
    export DOCKER_COMPOSE_VERSION=1.21.0

    # Update the apt package index.
    sudo apt-get update

    # Install packages to allow apt to use a repository over HTTPS.
    sudo apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common

    # Add Docker's official GPG key.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    # Verify the fingerprint.
    sudo apt-key fingerprint 0EBFCD88

    # Pick the release channel.
    sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    ${DOCKER_CHANNEL}"

    # Update the apt package index.
    sudo apt-get update

    # Install the latest version of Docker CE.
    sudo apt-get install -y docker-ce

    # Allow your user to access the Docker CLI without needing root.
    sudo usermod -aG docker $USER

    # Install Docker Compose.
    sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose &&
    sudo chmod 755 /usr/local/bin/docker-compose

    [[ $? ]] && e_success "Done"

}

install_docker_mac() {
    e_header "Installing Docker..."

    e_header "Checking status of desired Homebrew formulae..."
    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
        'docker'
        'docker-compose'
    )

    for index in ${!desired_formulae[*]}
    do
        if ! formula_exists ${desired_formulae[$index]}; then
            # Store the name (and options) of every missing formula
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        fi
    done

    if [[ "$missing_formulae" ]]; then
        # Convert the array of missing formula into a list of space-separate strings
        list_formulae=$( printf "%s " "${missing_formulae[@]}" )

        e_header "Installing missing Homebrew formulae..."
        # Install all missing formulae
        brew install $list_formulae
    fi
    [[ $? ]] && e_success "Done"

}

is_ubuntu && install_docker_ubuntu
is_mac && install_docker_mac

unset -f install_docker_ubuntu install_docker_mac
