#!/bin/bash

install_golang_ubuntu() {

    e_header "Installing Google GO..."
    sudo apt-get -y install golang-go go-dep
    [[ $? ]] && e_success "Done"

}

install_golang_mac() {
    e_header "Installing Google GO..."

    e_header "Updating Homebrew..."
    # Use the latest version of Homebrew
    brew update
    [[ $? ]] && e_success "Done"

    e_header "Updating any existing Homebrew formulae..."
    # Upgrade any already-installed formulae
    brew upgrade
    [[ $? ]] && e_success "Done"

    e_header "Checking status of desired Homebrew formulae..."
    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
        'golang'
    )

    for index in ${!desired_formulae[*]}
    do
        if ! formula_exists ${desired_formulae[$index]}; then
            # Store the name (and options) of every missing formula
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        fi
    done

    if [[ "$missing_formulae" ]]; then
        # Convert the array of missing formula into a list of space-separate strings
        list_formulae=$( printf "%s " "${missing_formulae[@]}" )

        e_header "Installing missing Homebrew formulae..."
        # Install all missing formulae
        brew install $list_formulae
    fi
    [[ $? ]] && e_success "Done"

    # Remove outdated versions from the Cellar
    e_header "Homebrew cleanup..."
    brew cleanup
    [[ $? ]] && e_success "Done"
    
}

is_ubuntu && install_golang_ubuntu
is_mac && install_golang_mac

unset -f install_golang_ubuntu install_golang_mac
