#!/bin/bash

install_golang_ubuntu() {

    e_header "Installing Google GO..."
    sudo apt-get -y install golang-go
    [[ $? ]] && e_success "Done"

}

install_golang_mac() {
    e_error "NOT YET IMPLEMENTED"
    exit 1
}

is_ubuntu && install_golang_ubuntu
is_mac && install_golang_mac

unset install_golang_ubuntu install_golang_mac
