#!/bin/bash

install_golang_ubuntu() {

    e_header "Installing Google GO..."
    sudo apt-get -y install golang-go go-dep
    [[ $? ]] && e_success "Done"

}

install_golang_mac() {
    e_header "Installing Google GO..."
    e_error "golang(mac): NOT YET IMPLEMENTED"
}

is_ubuntu && install_golang_ubuntu
is_mac && install_golang_mac

unset -f install_golang_ubuntu install_golang_mac
