#!/bin/bash

install_java_ubuntu() {

    e_header "Installing Java..."
    sudo apt-get -y install openjdk-11-jdk openjdk-11-demo openjdk-11-doc openjdk-11-jre-headless openjdk-11-source 
    sudo apt-get install maven

    [[ $? ]] && e_success "Done"

}

install_java_mac() {

    e_header "Installing Java..."

    brew tap homebrew/cask-versions

    install_cask_on_mac java11 adoptopenjdk
    install_on_mac maven

    [[ $? ]] && e_success "Done"

}

is_ubuntu && install_java_ubuntu
is_mac && install_java_mac

unset -f install_java_ubuntu install_java_mac
