#!/bin/bash

install_java_ubuntu() {

    e_header "Installing Java..."
    sudo apt-get -y install openjdk-11-jdk openjdk-11-demo openjdk-11-doc openjdk-11-jre-headless openjdk-11-source 
    sudo apt-get install maven

    [[ $? ]] && e_success "Done"

}

install_java_mac() {
    e_header "Installing Java..."

    brew tap homebrew/cask-versions

    e_header "Checking status of desired Homebrew formulae (cask) ..."
    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
        'java11'
        'adoptopenjdk'
    )

    for index in ${!desired_formulae[*]}
    do
        if ! formula_cask_exists ${desired_formulae[$index]}; then
            # Store the name (and options) of every missing formula
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        fi
    done

    if [[ "$missing_formulae" ]]; then
        # Convert the array of missing formula into a list of space-separate strings
        list_formulae=$( printf "%s " "${missing_formulae[@]}" )

        e_header "Installing missing Homebrew formulae (cask) ..."
        # Install all missing formulae
        brew cask install $list_formulae
    fi

    e_header "Checking status of desired Homebrew formulae..."
    local list_formulae_maven
    local -a missing_formulae_maven
    local -a desired_formulae_maven=(
        'maven'
    )

    for index in ${!desired_formulae_maven[*]}
    do
        if ! formula_exists ${desired_formulae_maven[$index]}; then
            # Store the name (and options) of every missing formula
            missing_formulae_maven=("${missing_formulae_maven[@]}" "${desired_formulae_maven[$index]}")
        fi
    done

    if [[ "$missing_formulae_maven" ]]; then
        # Convert the array of missing formula into a list of space-separate strings
        list_formulae_maven=$( printf "%s " "${missing_formulae_maven[@]}" )

        e_header "Installing missing Homebrew formulae..."
        # Install all missing formulae
        brew install $list_formulae_maven
    fi
    [[ $? ]] && e_success "Done"
}

is_ubuntu && install_java_ubuntu
is_mac && install_java_mac

unset -f install_java_ubuntu install_java_mac
