#!/bin/bash

install_node() {

    e_header "Installing NVM..."
    unset NVM_DIR
    curl -s -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [[ $? ]] && e_success "Done"

    e_header "Installing Node.js..."
    nvm install node
    nvm version > ${HOME}/.nvmrc
    [[ $? ]] && e_success "Done"

    e_header "Installing NPM..."
    local packages="npm"
    npm install $packages --global --quiet
    [[ $? ]] && e_success "Done"

}

install_node

unset -f install_node
