#!/bin/bash

install_python_ubuntu() {

    e_header "Installing Python..."

    sudo apt-get -y install python3 python3-pip
    pip3 install --user pipenv
    sudo python3 -m pip uninstall -y pip && sudo apt install python3-pip --reinstall

    sudo ln -s /usr/bin/python3 /usr/bin/python
    sudo ln -s /usr/bin/pip3 /usr/bin/pip

    [[ $? ]] && e_success "Done"

}

install_python_mac() {
    e_header "Installing Python..."

    e_header "Checking status of desired Homebrew formulae..."
    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
        'python'
    )

    for index in ${!desired_formulae[*]}
    do
        if ! formula_exists ${desired_formulae[$index]}; then
            # Store the name (and options) of every missing formula
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        fi
    done

    if [[ "$missing_formulae" ]]; then
        # Convert the array of missing formula into a list of space-separate strings
        list_formulae=$( printf "%s " "${missing_formulae[@]}" )

        e_header "Installing missing Homebrew formulae..."
        # Install all missing formulae
        brew install $list_formulae
    fi
    [[ $? ]] && e_success "Done"

}

is_ubuntu && install_python_ubuntu
is_mac && install_python_mac

unset -f install_python_ubuntu install_python_mac
