#!/bin/bash

install_python_ubuntu() {

    e_header "Installing Python..."

    sudo apt-get -y install python3 python3-pip
    pip3 install --user pipenv
    sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall

    sudo ln -s /usr/bin/python3 /usr/bin/python
    sudo ln -s /usr/bin/pip3 /usr/bin/pip

    [[ $? ]] && e_success "Done"

}

install_python_mac() {
    e_header "Installing Python..."
    e_error "python(mac): NOT YET IMPLEMENTED"
}

is_ubuntu && install_python_ubuntu
is_mac && install_python_mac

unset -f install_python_ubuntu install_python_mac
