#!/bin/bash

update-resolv-conf_ubuntu() {
    e_header "Update resolv.conf..."
    SEARCH="$1"
    if [ "$SEARCH" == "" ]; then
        printf "DNS search path entry is empty - Skipping\n"
        return
    fi
    printf "Add search entry '$SEARCH'\n"
    cat /etc/resolv.conf | grep -v search | sudo tee /etc/resolv.conf &> /dev/null
    echo "search $SEARCH" | sudo tee -a  /etc/resolv.conf &> /dev/null
    [[ $? ]] && e_success "Done"
}

is_ubuntu && update-resolv-conf_ubuntu "$DNS_SEARCH_PATH"

unset -f update-resolv-conf_ubuntu
