#!/bin/bash

install_ssh-ident_ubuntu() {

    e_header "Installing ssh-ident..."
     
    sudo curl -sSL https://goo.gl/MoJuKB -o /usr/local/bin/ssh-ident
    sudo chmod 0755 /usr/local/bin/ssh-ident
    sudo rm -f /usr/local/bin/ssh
    sudo ln -s /usr/local/bin/ssh-ident /usr/local/bin/ssh
    [[ $? ]] && e_success "Done"

}

install_ssh-ident_mac() {

    e_header "Installing ssh-ident..."

    curl -sSL https://goo.gl/MoJuKB -o /usr/local/bin/ssh-ident
    chmod 0755 /usr/local/bin/ssh-ident
    rm -f /usr/local/bin/ssh
    ln -s /usr/local/bin/ssh-ident /usr/local/bin/ssh
    [[ $? ]] && e_success "Done"

}

is_ubuntu && install_ssh-ident_ubuntu
is_mac && install_ssh-ident_mac

unset -f install_ssh-ident_ubuntu install_ssh-ident_mac
