#!/bin/bash

install_ssh-ident() {

    e_header "Installing ssh-ident..."
    sudo curl -sSL https://goo.gl/MoJuKB -o /usr/local/bin/ssh-ident
    sudo chmod 0755 /usr/local/bin/ssh-ident
    sudo ln -s /usr/local/bin/ssh-ident /usr/local/bin/ssh
    [[ $? ]] && e_success "Done"

}

install_ssh-ident

unset -f install_ssh-ident
