#!/bin/bash

install_yarn_ubuntu() {

    e_header "Installing Yarn..."
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update && sudo apt-get install --no-install-recommends yarn 
    [[ $? ]] && e_success "Done"

}

install_yarn_mac() {
    e_header "Installing Yarn..."

    e_header "Checking status of desired Homebrew formulae..."
    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
        'yarn --without-node'
    )

    for index in ${!desired_formulae[*]}
    do
        if ! formula_exists ${desired_formulae[$index]}; then
            # Store the name (and options) of every missing formula
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        fi
    done

    if [[ "$missing_formulae" ]]; then
        # Convert the array of missing formula into a list of space-separate strings
        list_formulae=$( printf "%s " "${missing_formulae[@]}" )

        e_header "Installing missing Homebrew formulae..."
        # Install all missing formulae
        brew install $list_formulae
    fi
    [[ $? ]] && e_success "Done"
}

is_ubuntu && install_yarn_ubuntu
is_mac && install_yarn_mac

unset -f install_yarn_ubuntu install_yarn_mac
