#!/bin/bash

function aws-switch() {
    case "${1}" in
        "" | clear)
            export AWS_PROFILE=""
            ;;
        *)
            export AWS_PROFILE="${1}"
            ;;
    esac
}

_aws-switch_completions()
{
    if [ "${#COMP_WORDS[@]}" != "2" ]; then
        return
    fi
    COMPREPLY=($(compgen -W "$( grep '\[profile' ~/.aws/config | awk '{sub(/]/, "", $2); print $2}' | while read -r profile; do echo -n "$profile "; done )" -- "${COMP_WORDS[1]}" ))
}

complete -F _aws-switch_completions aws-switch

