#!/bin/bash

for NODE_DIR in $NVM_DIR/versions/node/*/ ; do 
  COMPLETIONS_DIR=$NODE_DIR/lib/node_modules/serverless/node_modules/tabtab/.completions
      
  # tabtab source for serverless package
  # uninstall by removing these lines or running `tabtab uninstall serverless`
  [ -f $COMPLETIONS_DIR/serverless.bash ] && . $COMPLETIONS_DIR/serverless.bash
  
  # tabtab source for sls package
  # uninstall by removing these lines or running `tabtab uninstall sls`
  [ -f $COMPLETIONS_DIR/sls.bash ] && . $COMPLETIONS_DIR/sls.bash

done

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
#[ -f $NVM_DIR/versions/node/$(nvm current)/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . $NVM_DIR/versions/node/$(nvm current)/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash

# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
#[ -f $NVM_DIR/versions/node/$(nvm current)/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . $NVM_DIR/versions/node/$(nvm current)/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash
